In [1]:
import os
from sklearn import datasets
import sklearn.datasets
import sklearn.ensemble
import numpy as np


In [2]:
iris = sklearn.datasets.load_iris()

In [3]:
X=iris.data
Y=iris.target

In [4]:
X.shape

(150, 4)

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
Y.shape

(150,)

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
minmax_scaler.fit(X)

MinMaxScaler()

In [9]:
X=minmax_scaler.transform(X)

In [10]:
X

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [11]:
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(X, Y, train_size=0.90)

In [12]:
train.shape

(135, 4)

In [13]:
test.shape

(15, 4)

In [ ]:
labels_train

In [14]:
D = np.c_[train,labels_train]

In [ ]:
#os.chdir('/home/sunil/update-classifier')

In [15]:
np.savetxt('iris_train.csv', D, delimiter=",")

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import linear_model
import pandas as pd

clf = linear_model.SGDClassifier()

chunksize = 25
for chunk in pd.read_csv('iris_train.csv', header=None, chunksize=chunksize):
    train_sub = chunk
    print(train_sub)
    Y=train_sub[4]
    X=train_sub.drop([4], axis=1)
    clf.partial_fit(X,Y, classes=np.unique(Y))
    print(clf.coef_)
    clf.predict(test)
    pred=clf.predict(test)
    print(pred)
    print(accuracy_score(pred, labels_test))

           0         1         2         3    4
0   0.222222  0.708333  0.084746  0.125000  0.0
1   0.583333  0.500000  0.593220  0.583333  1.0
2   0.416667  0.291667  0.491525  0.458333  1.0
3   0.111111  0.500000  0.050847  0.041667  0.0
4   0.388889  0.333333  0.593220  0.500000  1.0
5   0.750000  0.500000  0.627119  0.541667  1.0
6   0.388889  1.000000  0.084746  0.125000  0.0
7   0.638889  0.416667  0.576271  0.541667  1.0
8   0.583333  0.333333  0.779661  0.875000  2.0
9   0.361111  0.291667  0.542373  0.500000  1.0
10  0.166667  0.208333  0.593220  0.666667  2.0
11  0.861111  0.333333  0.864407  0.750000  2.0
12  0.388889  0.750000  0.118644  0.083333  0.0
13  0.583333  0.333333  0.779661  0.833333  2.0
14  0.166667  0.166667  0.389831  0.375000  1.0
15  0.333333  0.125000  0.508475  0.500000  1.0
16  0.805556  0.666667  0.864407  1.000000  2.0
17  0.222222  0.750000  0.152542  0.125000  0.0
18  0.250000  0.625000  0.084746  0.041667  0.0
19  0.444444  0.500000  0.644068  0.7083

In [17]:
clf.predict(test)

array([0., 2., 0., 0., 0., 2., 2., 2., 2., 0., 2., 2., 2., 0., 2.])